### DISCUSSION TITLE
Is there a way to check the status and logs of a workflow submitted through hera?

### DISCUSSION THREAD

**Discussion by piby180** [argoproj-labs/hera#1356] [Q&A] [answered]
Basically the title. I can create a workflow with Hera. But I can't check the current status or the logs for the workflow

**Comment by elliotgunton** [comment, marked as answer]
Hey @piby180! The status is part of the workflow object that you get back from the `create` method, you can check it like so:
https://github.com/argoproj-labs/hera/blob/1567eae0f6ecbebf79d951fe04692015ffcb3648/tests/submissions/test_hello_world.py#L35-L36

The logs can be fetched through the `workflow_logs` function on the `WorkflowsService` https://github.com/argoproj-labs/hera/blob/1567eae0f6ecbebf79d951fe04692015ffcb3648/src/hera/workflows/service.py#L1056

_Sorry for the delay, we had a busy ArgoCon/KubeCon last week!_

**Comment by piby180** [comment]
Hi @elliotgunton 
Thank you for your answer.  I now understand that with wait=True, we create the workflow synchronously and when it is finished, we can get the status of the workflow. 

But how do we get the status of a workflow which was created asynchronously?

**Reply by elliotgunton** [reply]
You will need the name and namespace of the workflow, then you can use this https://github.com/argoproj-labs/hera/blob/23672c842719e520459f4fd2fafa3de0439b99b4/src/hera/workflows/service.py#L991-L997

**Comment by piby180** [comment]
@elliotgunton  Sorry for the delay. I was on vacation :) 
Thanks and it is working now except logs.

I am not able to fetch the logs. My workflow is storing logs to S3 as an artifact. 

```
from hera.workflows.service import WorkflowsService

s = WorkflowsService()
s.workflow_logs(name=wf_name)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[93], line 1
----> 1 s.workflow_logs(name=wf_name)

File ~\AppData\Local\anaconda3\Lib\site-packages\hera\workflows\service.py:1105, in WorkflowsService.workflow_logs(self, name, namespace, pod_name, container, 
follow, previous, since_seconds, seconds, nanos, timestamps, tail_lines, limit_bytes, insecure_skip_tls_verify_backend, grep, selector)
   1102 if resp.ok:
   1103     return V1alpha1LogEntry(**resp.json())
-> 1105 raise exception_from_server_response(resp)

File ~\AppData\Local\anaconda3\Lib\site-packages\hera\exceptions\__init__.py:84, in exception_from_server_response(resp)
     80 assert not resp.ok, "This function should only be called with non-2xx responses"
     81 try:
     82     return exception_from_status_code(
     83         resp.status_code,
---> 84         f"Server returned status code {resp.status_code} with message: `{resp.json()['message']}`",
     85     )
     86 except json.JSONDecodeError:
     87     return exception_from_status_code(
     88         resp.status_code,
     89         f"Server returned status code {resp.status_code} with message: `{resp.text}`",
     90     )

KeyError: 'message'
```

I tried s.pod_logs(wf_name, pod_name) but got the same error.

My k8s role has permissions to read pod logs. Ideally I want to get the link to the log file on S3. Thanks for your help :) 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: temp-argo-api-test
  namespace: argo-dev
rules:
  - apiGroups:
      - ""
    resources:
      - pods/logs
    verbs:
      - create
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
    verbs:
      - create
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - get
    resourceNames: ["workflow-template-submittable"]
   ```
