### DISCUSSION TITLE
en/stable/examples/workflows/upstream/volumes_emptydir/

### DISCUSSION THREAD

**Discussion by giscus** [argoproj-labs/hera#682] [Website Discussions]
# en/stable/examples/workflows/upstream/volumes_emptydir/

https://hera.readthedocs.io/en/stable/examples/workflows/upstream/volumes_emptydir/

**Comment by sourcx** [comment]
I'm trying to understand the Hera syntax but where is the @script here and the w.create()?
Also, is it me or does this example seem very verbose and not very idiomatic?

**Reply by flaviuvadan** [reply]
Hey @sourcx! There's no `script` here because the example uses a `container` template, not a `script` template. Also, `w.create()` is not added in examples because the workflows are not submitted to any Argo server in CI (yet).

For more context, the `w` variable is tested by Hera [hera](https://github.com/argoproj-labs/hera/blob/main/tests/test_examples.py#L84), and the tests compare examples with raw YAML examples from the upstream Argo Workflows repo

**Reply by flaviuvadan** [reply]
If you have questions about `script` usage I am happy to help!

**Reply by sourcx** [reply]
Thanks for the reply! I like the concept of Hera a lot but I'm not familiar enought with Argo yet to understand everything.I appreciate your offer to help, so here goes:

I'm in the process of converting an Argo workflow to Hera to see how that would work, it basically boils down to this:

```
kind: WorkflowTemplate
spec:
  - name: step1
    volumes:
    - name: workdir
      emptyDir: { }
    script:
      volumeMounts:
      - name: workdir
        mountPath: /workdir
```

So I was trying to use the `@script, with Workflow, with Steps`-syntax but could not figure out where to add the emptyDir.

**Reply by flaviuvadan** [reply]
In the YAML example above the `workdir` is set on the spec of the workflow template! In Hera something like 

```python
from hera.workflows import WorkflowTemplate, EmptyDirVolume, models as m, script

# the `volume_mounts` of the `script` informs Argo that this specific script template
# should mount the volume called `workdir` at path `/workdir` inside the script environment
@script(volume_mounts=[m.VolumeMount(name="workdir", mount_path="/workdir")])
def foo():
    print(42)


# here, the workflow template sets an empty dir "globally", at the workflow level
with WorkflowTemplate(name="my-wf-template", entrypoint="foo", volumes=EmptyDirVolume(name="workdir")) as w:
    foo()

print(w.to_yaml())
```

will print out 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-wf-template
spec:
  entrypoint: foo
  templates:
  - name: foo
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys
        # this gets added by Hera, can disable via `@script(..., add_cwd_to_sys_path=False)`
        sys.path.append(os.getcwd())

        print(42)'
      volumeMounts:
      - mountPath: /workdir
        name: workdir
  volumes:
  - emptyDir: {}
    name: workdir
```
