### ISSUE TITLE
SecretEnv not working in Template

### ISSUE THREAD

**Issue by roeizavida** [argoproj-labs/hera#1080]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [X] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [X] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
When using `SecretEnv` in a `Template`, it is not expanded and the resulting entry in `env` only contains the `name`.

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import (
    Container,
    Env,
    SecretEnv,
    WorkflowTemplate,
)
from hera.workflows.models import Template

whalesay = Container(
    image="docker/whalesay:latest",
    command=["cowsay"],
    env=[
        Env(name="test", value="1"),
        SecretEnv(name="s1", secret_key="s1", secret_name="abc"),
    ],
)
templates = [Template(name="test", container=whalesay)]
wt = WorkflowTemplate(name="test", templates=templates)
print(wt.templates[0].container.env)
```

Results:
```py
[EnvVar(name='test', value='1', value_from=None), EnvVar(name='s1', value=None, value_from=None)]
```

**Expected behavior**
`SecretEnv` should be expanded into `EnvVar` that it's `value_from` property is populated.

**Environment**
- Hera Version: 5.15.1
- Python Version: 3.10.13
- Argo Version: 3.5.6

**Comment by jeongukjae** [comment]
@roeizavida Hi, if workflow or workflowtemplate is used with proper syntax, it seems working as expected. Can you check this issue again?
You can check the example in here: https://hera-workflows.readthedocs.io/en/latest/examples/workflows/misc/init_containers_with_env/

```py
with Workflow(name="test") as wt:
    Container(
        image="docker/whalesay:latest",
        command=["cowsay"],
        env=[
            Env(name="test", value="1"),
            SecretEnv(name="s1", secret_key="s1", secret_name="abc"),
        ],
    )
print(wt.to_yaml())
```

output:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  templates:
  - container:
      command:
      - cowsay
      env:
      - name: test
        value: '1'
      - name: s1
        valueFrom:
          secretKeyRef:
            key: s1
            name: abc
      image: docker/whalesay:latest
```
