### ISSUE TITLE
CronWorkflow suspend: incorrect manifest 

### ISSUE THREAD

**Issue by DanCardin** [argoproj-labs/hera#1121]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [x] exporting to YAML
- [x] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
```python
CronWorkflow(
    name="foo",
    schedule="* * * * *",
    workflow_template_ref=models.WorkflowTemplateRef(name="bar"),
    suspend=True,
)
```

Generates:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: foo
spec:
  schedule: 0 */6 * * *
  workflowSpec:
    suspend: true
    workflowTemplateRef:
      name: bar
```

This does not prevent the workflow from being scheduled, as expected. Instead, it regularly schedules the workflows, but the workflow itself is suspended and stays running forever.

**Expected behavior**
As far as i can tell from the docs (and from clicking the suspend checkbox inside Workflows), it should generate

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: foo
spec:
  schedule: 0 */6 * * *
  suspend: true
  workflowSpec:
    workflowTemplateRef:
      name: bar
```

**Environment**
- Hera Version: 5.15.1
- Python Version: 3.10
- Argo Version: 3.5.1

---

As far as I can tell, this stems from https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/cron_workflow.py#L153 not special casing the `suspend` field, like it does the schedule field. 

It seems like it could be fixed by something alike:
```diff
        model_workflow = cast(_ModelWorkflow, super().build())
+        model_workflow.spec.suspend = None
        model_cron_workflow = _ModelCronWorkflow(
            metadata=model_workflow.metadata,
            spec=CronWorkflowSpec(
                schedule=self.schedule,
+                suspend=self.suspend,
                workflow_spec=model_workflow.spec,
            ),
        )
```
to exactly produce the above yaml. With the caveat, that if you **did** want the `suspend` inside `workflowSpec`, this makes that impossible, for whatever that's worth...

I can supply the PR if this makes sense?
