### ISSUE TITLE
CLI does not correctly generate script templates that use the runner

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#1161]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [x] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

_Error log if applicable_:
```
error: something broke!
```

**To Reproduce**
Full Hera code to reproduce the bug:

1. Create a folder with a Python file in it:
```
tree .
.
├── hera_example
│   ├── new_decorators.py
```

2. Add Python code (adapted from new_decorators_basic_script.py example)
```py
from hera.shared import global_config
from hera.workflows import Input, Output, WorkflowTemplate

global_config.experimental_features["decorator_syntax"] = True

w = WorkflowTemplate(name="my-template")

class MyInput(Input):
    user: str

@w.set_entrypoint
@w.script()
def hello_world(my_input: MyInput) -> Output:
    output = Output()
    output.result = f"Hello Hera User: {my_input.user}!"
    return output
```

3. Run `hera generate yaml hera_example/new_decorators.py` to get the following yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
spec:
  entrypoint: hello-world
  templates:
  - inputs:
      parameters:
      - name: user
    name: hello-world
    script:
      args:
      - -m
      - hera.workflows.runner
      - -e
      - new_decorators:hello_world
      command:
      - python
      env:
      - name: hera__script_annotations
        value: ''
      - name: hera__outputs_directory
        value: /tmp/hera-outputs
      - name: hera__script_pydantic_io
        value: ''
      image: python:3.8
      source: '{{inputs.parameters}}'
```

Notice that the entrypoint is not `hera_example.new_decorators:hello_world`, meaning this script would not work as it won't find the module/file when installed in a Docker container.

**Expected behavior**
_A clear and concise description of what you expected to happen:_

`hera generate` should match `w.to_yaml()` output with full module path:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
spec:
  entrypoint: hello-world
  templates:
  - inputs:
      parameters:
      - name: user
    name: hello-world
    script:
      args:
      - -m
      - hera.workflows.runner
      - -e
      - hera_example.new_decorators:hello_world
      command:
      - python
      env:
      - name: hera__script_annotations
        value: ''
      - name: hera__outputs_directory
        value: /tmp/hera-outputs
      - name: hera__script_pydantic_io
        value: ''
      image: python:3.8
      source: '{{inputs.parameters}}'
```

**Environment**
- `hera[experimental]==5.16.2`
- Python Version: 3.12.4

**Additional context**
