### ISSUE TITLE
New dag/steps decorators generate incorrect valueFrom and lose output descriptions

### ISSUE THREAD

**Issue by alicederyn** [argoproj-labs/hera#1218]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [X] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [X] Yes

**3. This bug occurs in Hera when...**
- [X] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
`description` is being dropped from `Parameter` annotations on `Output` types when using `@wt.steps` decorator and similar.

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from typing import Annotated
from hera.shared import global_config
from hera.workflows import Input, Output, Parameter, Workflow

global_config.experimental_features["decorator_syntax"] = True

class ExampleOutput(Output):
  field: Annotated[str, Parameter(description="Some field")]

w = Workflow(name="my-workflow")

@w.script()
def my_script(_: Input) -> ExampleOutput:
  return ExampleOutput(field="Hello world!")

@w.steps()
def steps(_: Input) -> ExampleOutput:
  result = my_script(Input())
  return ExampleOutput(field=result.field)
```

**Expected behavior**
The following YAML for the step output:

```yaml
      - description: Some field
        name: field
        valueFrom:
          parameter: '{{steps.result.outputs.parameters.field}}'
 ```

What I'm actually seeing is:

```yaml
      - name: field
        valueFrom:
          parameter: '{{steps.result.outputs.parameters.None}}'
 ```

**Environment**
- Hera Version: 5.17.0
- Python Version: 3.11.8
- Argo Version: N/A

**Additional context**
I believe the name is being mistakenly set to `None` here: https://github.com/argoproj-labs/hera/blob/d75a1b3ff60dd776bc499b91e08e0d94b8eed95f/src/hera/workflows/_mixins.py#L744

And the description is being discarded here: https://github.com/argoproj-labs/hera/blob/d75a1b3ff60dd776bc499b91e08e0d94b8eed95f/src/hera/workflows/io/_io_mixins.py#L229
