### ISSUE TITLE
Cannot set default values for workflow template arguments

### ISSUE THREAD

**Issue by tzielaski** [argoproj-labs/hera#1268]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [x] Yes

**3. This bug occurs in Hera when...**
- [x] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
Setting default values for workflow template's arguments doesn't work but is supported by Argo if specified directly in the YAML.

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import DAG, script, WorkflowTemplate, Parameter


@script()
def foo(a, b=42, c=None):
    print(a, b, c)


with WorkflowTemplate(
        name="test-default-param",
        entrypoint="d",
        arguments=[
            Parameter(name='a', default='1', description='This should have a default')
        ]
) as w:
    with DAG(
            name="d",
            inputs=[
                Parameter(name='a', default='1')
            ]):
        foo(name="b-unset-c-unset", arguments={"a": "{{ inputs.parameters.a }}"})

```

generates
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-default-param
spec:
  arguments:
    parameters:
    - description: This should have a default
      name: a
  entrypoint: d
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: a
            value: '{{ inputs.parameters.a }}'
        name: b-unset-c-unset
        template: foo
    inputs:
      parameters:
      - default: '1'
        name: a
    name: d
  - inputs:
      parameters:
      - name: a
      - default: '42'
        name: b
      - default: 'null'
        name: c
    name: foo
    script:
      command:
      - python
      image: python:3.8
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: a = json.loads(r'''{{inputs.parameters.a}}''')
        except: a = r'''{{inputs.parameters.a}}'''
        try: b = json.loads(r'''{{inputs.parameters.b}}''')
        except: b = r'''{{inputs.parameters.b}}'''
        try: c = json.loads(r'''{{inputs.parameters.c}}''')
        except: c = r'''{{inputs.parameters.c}}'''

        print(a, b, c)
```
The default value is not present in the UI:
<img width="375" alt="image" src="https://github.com/user-attachments/assets/0e6bde2d-b2a5-47f9-a74e-62f5ab3000f7">

**Expected behavior**
The generated YAML contains default values:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-default-param
spec:
  arguments:
    parameters:
    - description: This should have a default
      default: '1'
      name: a
  entrypoint: d
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: a
            value: '{{ inputs.parameters.a }}'
        name: b-unset-c-unset
        template: foo
    inputs:
      parameters:
      - default: '1'
        name: a
    name: d
  - inputs:
      parameters:
      - name: a
      - default: '42'
        name: b
      - default: 'null'
        name: c
    name: foo
    script:
      command:
      - python
      image: python:3.8
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: a = json.loads(r'''{{inputs.parameters.a}}''')
        except: a = r'''{{inputs.parameters.a}}'''
        try: b = json.loads(r'''{{inputs.parameters.b}}''')
        except: b = r'''{{inputs.parameters.b}}'''
        try: c = json.loads(r'''{{inputs.parameters.c}}''')
        except: c = r'''{{inputs.parameters.c}}'''

        print(a, b, c)
```
and the default value is set in Argo UI
<img width="328" alt="image" src="https://github.com/user-attachments/assets/2e19c1ea-172c-4f27-90b0-302b40eb51a2">

**Environment**
- Hera Version: 5.16.2
- Python Version: 3.12.5
- Argo Version: 3.6.0
