### ISSUE TITLE
`pod_gc` on `WorkflowTemplate` is not renedered correctly

### ISSUE THREAD

**Issue by seyhbold** [argoproj-labs/hera#1292]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [x] Yes

**3. This bug occurs in Hera when...**
- [x] exporting to YAML
- [x] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
I am using `WorkflowTemplate` with `pod_gc`

```python
from hera.workflows import WorkflowTemplate, models as m

with WorkflowTemplate(
    name=name,
    ...
    pod_gc=m.PodGC(
        delete_delay_duration=m.Duration(duration="5m"),
        strategy="OnWorkflowCompletion",
    ),
```

rendering the yaml of this gives:
```yaml
  imagePullSecrets:
  - name: regcred
  podGC:
    deleteDelayDuration:
      duration: 5m
    strategy: OnWorkflowCompletion
```

According to https://argo-workflows.readthedocs.io/en/latest/fields/#podgc 

it should render as:
```yaml
  imagePullSecrets:
  - name: regcred
  podGC:
    deleteDelayDuration: "5m"
    strategy: OnWorkflowCompletion
```

`deleteDelayDuration` should be a string and not a `Duration` object

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import WorkflowTemplate, models as m

with WorkflowTemplate(
    pod_gc=m.PodGC(
        delete_delay_duration=m.Duration(duration="5m"),
        strategy="OnWorkflowCompletion"
    )
) as template:
    pass

print(template.to_yaml())
```

**Expected behavior**
render 
```yaml
...
podGC:
  deleteDelayDuration: "5m"
  strategy: OnWorkflowCompletion
...
```

**Environment**
- Hera Version: 5.18.0
- Python Version: 3.13.1
- Argo Version: 3.6.2

Could you please give me a hint how to fix that?
