### ISSUE TITLE
Cannot combine Artifacts and Parameters in a single dictionary of Step/Task arguments

### ISSUE THREAD

**Issue by jplrts** [argoproj-labs/hera#1315]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [X] Yes

**3. This bug occurs in Hera when...**
- [X] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

When I build a Step with a combination of regular Parameters and Artifacts then Hera generates the input arguments with a parameter list only. I checked the code in `_build_arguments()` in `_mixins.py` and the arguments dict generates output for parameters only. At our company we do use quite some workflow templates that mix both without issues so this seems to be a limitation/bug in Hera. 

I'm willing to submit a fix in case there is a chance that it can be reviewed and merged.

Output of the step below where I tried to combine a `msg` artifact with a set of 3 regular parameters
```
 steps:
    - - name: build-fetcher-request-message
        template: build-fetcher-request
    - - arguments:
          parameters:
          - name: method
            value: MarketDataFetcher.FetchMarketData
          - name: s3_prefix
            value: s3://bucket
          - name: serverip
            value: localhost
          - name: msg
            value: '{"name": "payload", "archive": null, "archive_logs": null, "artifact_gc":
              null, "deleted": null, "from_": "{{steps.build-fetcher-request-message.outputs.artifacts.payload}}",
              "from_expression": null, "global_name": null, "mode": null, "path":
              null, "recurse_mode": null, "sub_path": null, "loader": null, "optional":
              null, "output": false}'
        name: market-data-fetcher
        template: run-fetcher

```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import WorkflowTemplate, Steps, Step, Container, Artifact, Parameter, RawArtifact

with WorkflowTemplate(name=self.name, generate_name=self.generate_name,
                      entrypoint=self.entrypoint) as w:
    fetcher_template = Container(
            name="build-fetcher-request",
            source=f"""
            set -o pipefail
            echo '{{"arguments": {{"message": "Hello"}}}}' > /tmp/payload.json
              """,
            image="alpine:3.12",
            command=["sh"],
            outputs=[Artifact(name="payload", path="/tmp/payload.json")],
        )

    bul_fetcher_template = Container(
        name="run-fetcher",
        source=f"""
            set -o pipefail
            cat /tmp/msg.json | grpcurl -use-reflection -emit-defaults -d '@' '{{input.arguments.message}}:50051' '$method' > /tmp/response.json
              """,
        image="fullstorydev/grpcurl:latest-alpine",
        command=["sh"],
        outputs=[Artifact(name="response", path="/tmp/response.json")],
        inputs=[
            Parameter(name="method"),
            Parameter(name="s3_prefix"),
            Parameter(name="serverip"),
            RawArtifact(
                data="bla",
                name="msg",
                path="/tmp/msg.json",
            )
        ],
    )
    # Define two steps, last one depending on the output artifact of the first
    with Steps(name="fetchers"):
        request_step = Step(name="build-fetcher-request-message", template=fetcher_template)
        Step(name="market-data-fetcher", template=bul_fetcher_template,
                            arguments={ "method": "method
                                       "s3_prefix": "s3://bucket",
                                       "serverip": "localhost",
                                       "msg": request_step.get_artifact('payload')})
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_
I would expect the yaml for this workflow to output this

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: bess-optimisation-dk-
  name: bess-optimisation-dk
spec:
  entrypoint: build-fetcher-request-message
  templates:
  - container:
      command:
      - sh
      image: alpine:3.12
    name: build-fetcher-request
    outputs:
      artifacts:
      - name: payload
        path: /tmp/payload.json
  - container:
      command:
      - sh
      image: fullstorydev/grpcurl:latest-alpine
    inputs:
      artifacts:
      - name: msg
        path: /tmp/msg.json
        raw:
          data: bla
      parameters:
      - name: method
      - name: s3_prefix
      - name: serverip
    name: run-fetcher
    outputs:
      artifacts:
      - name: response
        path: /tmp/response.json
  - name: fetchers
    steps:
    - - name: build-fetcher-request-message
        template: build-fetcher-request
    - - arguments:
          parameters:
          - name: method
            value: MarketDataFetcher.FetchMarketData
          - name: s3_prefix
            value: s3://bucket
          - name: serverip
            value: localhost
          artifacts:
          - name: msg
            from: '{{steps.build-fetcher-request-message.outputs.artifacts.payload}}'
        name: market-data-fetcher
        template: run-fetcher
```

**Environment**
- Hera Version: 5.1.19
- Python Version: 3.12.8
- Argo Version: 3.5.12

**Additional context**
