### ISSUE TITLE
ArgoWorkflow as Backend for Wurzel using Hera. Wrong references in Artifacts

### ISSUE THREAD

**Issue by tweigel-dev** [argoproj-labs/hera#1398]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [x] Yes

**3. This bug occurs in Hera when...**
- [ ] exporting to YAML
- [x] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>
Hay folks, thanks for the amazing lib.

We are the maintainer of [wurzel](https://github.com/telekom/wurzel). A RAG first pipelining tool, which is currently supporting [DVC](https://github.com/iterative/dvc).
But we would like to extend our support for other pipelining backends like ArgoWorkflow. For that we started using hera.

wurzel works in a way that is specifies **TypedSteps** which has pydantic defined datastructures in between. One can then chain Steps by with fitting datastructures. Now the question:
In DVC we had one shared file system, so we only had to share the paths. In ArgoWorkflow we have to share the path and explain to ArgoWorkflows to mount the outputs and inputs accordingly in addition.

our [backend](https://github.com/telekom/wurzel/blob/feature/argo_workflow/wurzel/backend/backend_argo.py#75250b4) is now generating Workflow yamls like the following.

Following a abstract visulaization how they are chained
``` python
    doc =DoclingStep
    splitter =SimpleSplitterStep
    duplication =DropDuplicationStep
    doc >> splitter >> duplication

    y = backend().generate_yaml(duplication)
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wurzel
spec:
  entrypoint: wurzel-pipeline
  templates:
  - name: wurzel-pipeline
    dag:
      tasks:
      - name: DoclingStep
        template: wurzel-run-DoclingStep
        arguments:
          parameters:
          - name: inputs
            value: '[]'
      - name: SimpleSplitterStep
        depends: DoclingStep
        template: wurzel-run-SimpleSplitterStep
        arguments:
          parameters:
          - name: inputs
            value: '["{{tasks.DoclingStep.outputs.artifacts.wurzel-artifact}}"]'
      - name: DropDuplicationStep
        depends: SimpleSplitterStep
        template: wurzel-run-DropDuplicationStep
        arguments:
          parameters:
          - name: inputs
            value: '["{{tasks.SimpleSplitterStep.outputs.artifacts.wurzel-artifact}}"]'
  - name: wurzel-run-DoclingStep
    container:
      image: ghcr.io/telekom/wurzel
      command:
      - wurzel
      - run
      - wurzel.steps.docling.docling_step:DoclingStep
      - -o
      - data/DoclingStep
      - ''
      - ''
      - --encapsulate-env
    inputs:
      parameters:
      - name: inputs
    outputs:
      artifacts:
      - name: wurzel-artifact
        path: /tmp/DoclingStep
  - name: wurzel-run-SimpleSplitterStep
    container:
      image: ghcr.io/telekom/wurzel
      command:
      - wurzel
      - run
      - wurzel.steps.splitter:SimpleSplitterStep
      - -o
      - data/SimpleSplitterStep
      - ''
      - -i
      - '{{tasks.DoclingStep.outputs.artifacts.wurzel-artifact}}'
      - --encapsulate-env
    inputs:
      parameters:
      - name: inputs
    outputs:
      artifacts:
      - name: wurzel-artifact
        path: /tmp/SimpleSplitterStep
  - name: wurzel-run-DropDuplicationStep
    container:
      image: ghcr.io/telekom/wurzel
      command:
      - wurzel
      - run
      - wurzel.steps.duplication:DropDuplicationStep
      - -o
      - data/DropDuplicationStep
      - ''
      - -i
      - '{{tasks.SimpleSplitterStep.outputs.artifacts.wurzel-artifact}}'
      - --encapsulate-env
    inputs:
      parameters:
      - name: inputs
    outputs:
      artifacts:
      - name: wurzel-artifact
        path: /tmp/DropDuplicationStep
```
The Problem is now, that according to argoWorkflow the references are not valid and its not clear why hera is generating these paths invalid, although the Artifacts are passed as in the examples. 

**Environment**
- Hera Version: 5.20.1
- Python Version: 3.11.11
- Argo Version: 3.5.11
