### ISSUE TITLE
Script runner constructor doesn't work well when invoked from main

### ISSUE THREAD

**Issue by mshatkhin23** [argoproj-labs/hera#573]
Tried defining a WT with a script using the runner constructor like this:
```python
global_config.set_class_defaults(Script, constructor="runner")
global_config.experimental_features["script_runner"] = True

@script()
def echo(message: str) -> None:
    """Prints out a message."""
    print(message)

def get_workflow_template() -> WorkflowTemplate:
    """Define your WorkflowTemplate in this function."""
    with WorkflowTemplate(name="my-name") as wt:
        echo(arguments={"message": "Hello world"})
        return wt

if __name__ == "__main__":
    wt = get_workflow_template()
    wt.to_file('/some/dir/', "workflow-template")
```

and received a generated yaml like this:
```yaml
...
name: echo
script:
  args:
    - -m
    - hera.workflows.runner
    - -e
    - __main__:echo
    command:
    - python
    image: ...
    source: '{{inputs.parameters}}'
```

where the `__module__` attr of the script's callable source was taken to be the top-level environment when executing the script with something like `python -m path.to.workflow_template`.

I resolved the issue by placing the yaml generating logic in a different python module and importing the workflow template definition (probably good practice either way), but I guess the runner constructor should be a bit more robust to these types of invocations.
