### ISSUE TITLE
ContainerNode: env and env_from not generating correct yaml

### ISSUE THREAD

**Issue by andef** [argoproj-labs/hera#631]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [ ] running Hera code and submitting to Argo

<h2>Bug report</h2>

**When using a ContainerNode, env/env_from the yaml is not generated properly**

**To Reproduce**
Adapted this [example](https://github.com/argoproj-labs/hera/blob/main/docs/examples/workflows/env.md) to use a ContainerSet:
```py
from hera.workflows import (
    ConfigMapEnv,
    ConfigMapEnvFrom,
    ContainerNode,
    ContainerSet,
    Env,
    ResourceEnv,
    SecretEnv,
    SecretEnvFrom,
    Workflow,
)

with Workflow(generate_name="secret-env-from-", entrypoint="whalesay") as w:
    with ContainerSet(name="whalesay"):
        ContainerNode(
            name="node",
            image="docker/whalesay:latest",
            command=["cowsay"],
            env_from=[
                SecretEnvFrom(prefix="abc", name="secret", optional=False),
                ConfigMapEnvFrom(prefix="abc", name="configmap", optional=False),
            ],
            env=[
                Env(name="test", value="1"),
                SecretEnv(name="s1", secret_key="s1", secret_name="abc"),
                ResourceEnv(name="r1", resource="abc"),
                ConfigMapEnv(name="c1", config_map_key="c1", config_map_name="abc"),
            ],
        )
print(w.to_yaml())
```
**Generates the following output:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-env-from-
spec:
  entrypoint: whalesay
  templates:
  - containerSet:
      containers:
      - command:
        - cowsay
        env:
        - name: test
          value: '1'
        - name: s1
        - name: r1
        - name: c1
        envFrom:
        - prefix: abc
        - prefix: abc
        image: docker/whalesay:latest
        name: node
    name: set
```
**Expected output:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-env-from-
spec:
  entrypoint: whalesay
  templates:
  - containerSet:
      containers:
      - command:
        - cowsay
        env:
        - name: test
          value: '1'
        - name: s1
          valueFrom:
            secretKeyRef:
              key: s1
              name: abc
        - name: r1
          valueFrom:
            resourceFieldRef:
              resource: abc
        - name: c1
          valueFrom:
            configMapKeyRef:
              key: c1
              name: abc
        envFrom:
        - prefix: abc
          secretRef:
            name: secret
            optional: false
        - configMapRef:
            name: configmap
            optional: false
          prefix: abc
        image: docker/whalesay:latest
        name: node
    name: whalesay
```

**Environment**
 - OS: Ubuntu
 - Browser: Firefox
 - Version of Hera: 5.2.0
 - Version of Argo: 3.2.11
