### ISSUE TITLE
Add Arguments Parameters From Configmap for Scripts

### ISSUE THREAD

**Issue by dejamiko** [argoproj-labs/hera#704]
There doesn't seem to be a way to use a parameter from configmap in a script now and have that Python function unit testable.

We'd need to create some sort of mocking system for allowing the unit testing or change the behaviour of the yaml generation (ignore subsequent usages of a parameter if it has a valueFrom?)

A Hera example of Arguments Parameters From Configmap within a container.
https://hera.readthedocs.io/en/stable/examples/workflows/upstream/arguments_parameters_from_configmap/
And the corresponding yaml
https://github.com/argoproj/argo-workflows/blob/master/examples/arguments-parameters-from-configmap.yaml

We would like to do something like:

```python
@script(inputs=[parameter(name="message", value_from=m.ValueFrom(
                config_map_key_ref=m.ConfigMapKeySelector(
                    name="simple-parameters",
                    key="msg",
                )
            ))])
def echo(message):
    print(message)
```

which behaves like a normal python function and generates a similar yaml

The current behaviour is that if we have the argument in the function signature, it will not take it from the configmap

```python
@script(inputs=[Parameter(name="a_string", value_from=ValueFrom( config_map_key_ref=ConfigMapKeySelector(
                    name="simple-parameters",
                    key="a_string_param"
                )))])
def echo_string(a_string):
    print(a_string)
```

```yaml
- inputs:
      parameters:
      - name: a_string
        valueFrom:
          configMapKeyRef:
            key: a_string_param
            name: simple-parameters
    name: echo-string
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        import json

        try: a_string = json.loads(r''''''{{inputs.parameters.a_string}}'''''')

        except: a_string = r''''''{{inputs.parameters.a_string}}''''''


        print(a_string)'
```
 and if we remove that parameter we get the correct yaml

```python
@script(inputs=[Parameter(name="an_int", value_from=ValueFrom( config_map_key_ref=ConfigMapKeySelector(
                    name="simple-parameters",
                    key="an_int_param"
                )))])
def echo_int():
    print("{{inputs.parameters.an_int}}")
```

```yaml
  - inputs:
      parameters:
      - name: an_int
        valueFrom:
          configMapKeyRef:
            key: an_int_param
            name: simple-parameters
    name: echo-int
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        print(''{{inputs.parameters.an_int}}'')'
```

but the function cannot be tested locally.
