### ISSUE TITLE
Enums of bools are not serialized

### ISSUE THREAD

**Issue by dejamiko** [argoproj-labs/hera#706]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [ ] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When using inputs inside a script decorator, enums of bools are saved as strings "True" and "False" and are not actual bools anymore. 

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Workflow, Parameter, script

@script(inputs=[Parameter(name="a_bool", enum=[True, False], default=False)])
def echo_boolean(a_bool: bool=False):
    print(a_bool and True)

with Workflow(name="my-workflow") as w:
    echo_boolean()
```

produces 

```yaml
- inputs:
      parameters:
      - default: 'false'
        enum:
        - 'True'
        - 'False'
        name: a_bool
    name: echo-boolean
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        import json

        try: a_bool = json.loads(r''''''{{inputs.parameters.a_bool}}'''''')

        except: a_bool = r''''''{{inputs.parameters.a_bool}}''''''


        print(a_bool and True)'
```

**Expected behavior**
We expect the enum to behave the same way as default and produce 

```yaml
- inputs:
      parameters:
      - default: 'false'
        enum:
        - 'true'
        - 'false'
        name: a_bool
    name: echo-boolean
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        import json

        try: a_bool = json.loads(r''''''{{inputs.parameters.a_bool}}'''''')

        except: a_bool = r''''''{{inputs.parameters.a_bool}}''''''


        print(a_bool and True)'
```
