### ISSUE TITLE
Argument-less examples break using the script runner

### ISSUE THREAD

**Issue by lancour** [argoproj-labs/hera#724]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
script decorated functions with no arguments break using the script runner setting

_Error log if applicable_:
```
Traceback (most recent call last):
  File "/opt/dyno/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/dyno/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/dyno/venv/lib/python3.10/site-packages/hera/workflows/runner.py", line 138, in <module>
    _run()
  File "/opt/dyno/venv/lib/python3.10/site-packages/hera/workflows/runner.py", line 131, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/opt/dyno/venv/lib/python3.10/site-packages/hera/workflows/runner.py", line 100, in _runner
    for kwarg in kwargs_list:
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
Full Hera code to reproduce the bug: This involves two files, one which has the scripts, and the other which is creating the workflow
```py
from hera.shared import GlobalConfig
GlobalConfig.set_class_defaults(Script, constructor="runner")
GlobalConfig.experimental_features["script_runner"] = True

@script()
def generate():
    # this can be anything! e.g fetch from some API, then in parallel process all entities; chunk database records
    # and process them in parallel, etc.
    json.dump([i for i in range(10)], sys.stdout)

@script()
def consume(value: int):
    print("Received value: {value}!".format(value=value))
    
# second file
from <something> import consume, generate
from hera.workflows import DAG, Workflow

# assumes you used `hera.set_global_token` and `hera.set_global_host` so that the workflow can be submitted
with Workflow(generate_name="dynamic-fanout-", entrypoint="d") as w:
    with DAG(name="d"):
        g = generate()
        c = consume(with_param=g.result)
        g >> c

w.create()
```

**Expected behavior**
This is exactly the example from here: https://hera.readthedocs.io/en/stable/examples/workflows/dynamic_fanout/ re-structured to be a pattern that a script runner can use. script runners seem to always break whenever I have empty kwarg examples, in this case, generate(). I can get this to work by adding a dummy argument to generate().

**Environment**
 - OS: iOS
 - Browser: chrome
 - Version of Hera: 5.6.0

**Additional context**
This tends to be pretty consistently reproducible - it is likely as simple as the script runner code needing to do a check for None on the kwargs before trying to iterate it

**Comment by elliotgunton** [comment]
The root cause is that the runner will pass `source: '{{inputs.parameters}}'` but for a script with no inputs, it sees `inputs: {}`, which substitutes Argo's `None` (`null`?) in. We can then see the runner gets `None`, despite the kwargs_list being initialised like so https://github.com/argoproj-labs/hera/blob/cd253fb03301c5974faa79b5eaf02dbe832379ec/src/hera/workflows/runner.py#L268


We can confirm with an inline script like so:

Test yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations: {}
  name: test-inputs-parameters-9sdns
spec:
  entrypoint: hello
  templates:
    - inputs: {}
      metadata: {}
      name: hello
      outputs: {}
      script:
        command:
          - python
        image: python:3.9
        name: ''
        resources: {}
        source: |-
          import os
          import sys
          sys.path.append(os.getcwd())
          import json
          p = json.loads(r'''{{inputs.parameters}}''')
          print('inputs.parameters={p}'.format(p=p))
  ttlStrategy: {}
```

Log contains:
```console
inputs.parameters=None
```
