### ISSUE TITLE
image_pull_policy doesn't work in UserContainers

### ISSUE THREAD

**Issue by abschm** [argoproj-labs/hera#797]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_
Using image_pull_policy in a UserContainer doesn't work. If you try, the workflow submits fine but imagePullPolicy doesn't show up in the submitted manifest. When using to_file() to see the YAML, the key shows up as "image_pull_policy" instead of imagePullPolicy and the workflow cannot be submitted with error `Failed to parse workflow: json: unknown field "image_pull_policy"`. When changing the YAML to imagePullPolicy and submitting manually, everything works as expected.

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Container, Workflow, UserContainer
from hera.workflows.models import ImagePullPolicy

with Workflow(
    generate_name="sidecar-hera5-",
    entrypoint="echo",
) as w:
    echo = Container(
        name="echo",
        image="appropriate/curl",
        command=["sh", "-c"],
        args=[
            "until `curl -G 'http://127.0.0.1/' >& /tmp/out`; do echo sleep && sleep 1; done && cat /tmp/out"
        ],
        sidecars=[
            UserContainer(
                name="nginx",
                image="nginx:1.13",
                command=["nginx", "-g", "daemon off;"],
                image_pull_policy=ImagePullPolicy.always,
            )
        ],
    )
w.to_file()
w.create()

```

Result of to_yaml():
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sidecar-hera5-
spec:
  entrypoint: echo
  templates:
  - container:
      args:
      - until `curl -G 'http://127.0.0.1/' >& /tmp/out`; do echo sleep && sleep 1;
        done && cat /tmp/out
      command:
      - sh
      - -c
      image: appropriate/curl
    name: echo
    sidecars:
    - command:
      - nginx
      - -g
      - daemon off;
      image: nginx:1.13
      image_pull_policy: Always
      name: nginx
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_
I expected image_pull_policy in a UserContainer to become imagePullPolicy in the YAML and show up in the final submitted manifest. Also ideally I wish Hera would throw an error or warning if the manifest contains invalid YAML so elements would not just disappear between Hera and Argo.

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version of Hera: 5.7.3
 - Version of Argo: 3.2.4
