### ISSUE TITLE
Hera fails when a script receives list of pydantic objects as list of expressions

### ISSUE THREAD

**Issue by halilbilgin** [argoproj-labs/hera#827]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [x] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [ ] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>
Hera script input serialization fails when a script receives a list of pydantic objects as expressions

```python
x_dataset = x_dataset_config().result
y_dataset = y_dataset_config().result

# this doesn't work
train_model(name="train-model-fails", arguments={"dataset_configs": [x_dataset, y_dataset]}).result
```
Where `x_dataset_config`, `y_dataset_config` and `train_model` are script callables, train-model step receives the following error while serializing the input:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/hera/workflows/runner.py", line 313, in <module>
    _run()
  File "/usr/local/lib/python3.9/site-packages/hera/workflows/runner.py", line 306, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/usr/local/lib/python3.9/site-packages/hera/workflows/runner.py", line 280, in _runner
    return function(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/hera/workflows/runner.py", line 37, in inner
    return f(**filtered_kwargs)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 130, in pydantic.decorator.ValidatedFunction.init_model_instance
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TrainModel
dataset_configs
  value is not a valid list (type=type_error.list)
```
The value of the input parameter `ranking_dataset_configs` `train_model` receives is as follows
```
["{"filename": "x"}", "{"filename": "y"}"]
```
**Describe the bug**
Double quotes in the expression values are not escaped in Argo, which causes an issue.
Above, `train_model` script receives a list of configs which is equivalent to `["{{steps.x-dataset-config.outputs.result}}",
              "{{steps.y-dataset-config.outputs.result}}"]`. However, Argo doesn't escape the quotes in the expression values so the evaluated list becomes:
 `["{"filename": "x"}", "{"filename": "y"}"]` so, hera fails to serialize this since this is not a valid json dump.

**To Reproduce**
Full Hera code to reproduce the bug:
```python
from hera.workflows import WorkflowsService, Container, Parameter, Workflow, script, Steps, Script
import json
from pydantic import BaseModel
from typing import List
from hera.shared import global_config

global_config.set_class_defaults(Script, constructor="runner")
global_config.experimental_features["script_runner"] = True
global_config.image = "hbilgin123/example_hera"
global_config.script_command = ["python"]

class DatasetConfig(BaseModel):
    filename: str


@script(constructor="runner")
def x_dataset_config() -> DatasetConfig:
    return DatasetConfig(filename="x")


@script(constructor="runner")
def y_dataset_config() -> DatasetConfig:
    return DatasetConfig(filename="y")

@script(constructor="runner")
def escape_quotes(data: dict) -> str:
    return json.dumps(data).replace('"', '\\"')


@script(constructor="runner")
def train_model_fails(dataset_configs: List[DatasetConfig]) -> str:
    return "Some model training has been done here"


@script(constructor="runner")
def train_model_works(dataset_configs: List[str]) -> str:
    processed_configs = [DatasetConfig.parse_raw(raw_config) for raw_config in dataset_configs]
    return "Some model training has been done here"


with Workflow(
    generate_name="arguments-parameters-",
    entrypoint="try",
    namespace="argo",
    workflows_service=WorkflowsService(host="https://127.0.0.1:2746", verify_ssl=False),
) as w:
    with Steps(name="try") as s:
        x_dataset = x_dataset_config().result
        y_dataset = y_dataset_config().result
        escaped_datasets = [escape_quotes(name='escape-x', arguments={'data': x_dataset}).result, escape_quotes(name='escape-y', arguments={'data': y_dataset}).result]

        with s.parallel():
            # this works
            train_model_works(name="train-model-works", arguments={"dataset_configs": escaped_datasets}).result

            # this doesn't work
            train_model_fails(name="train-model-fails-1", arguments={"dataset_configs": [x_dataset, y_dataset]}).result

            # this doesn't work neither
            train_model_fails(name="train-model-fails-2", arguments={"dataset_configs": escaped_datasets}).result
```

**Expected behavior**
The `train-model-fails-1` step above could have worked without any additional change.

**My current workaround**
Escaping double quotes and serializing `dataset_configs` manually as it is shown in the example above (i.e. `train-model-works` step)

**Environment**
 - OS: Windows, WSL2 (minikube)
 - Browser: Chrome
 - Version of Hera: 5.9.0
 - Version of Argo: 3.4.5

**Additional context**

**Comment by halilbilgin** [comment]
Yaml template
```
name: try
inputs: {}
outputs: {}
metadata: {}
steps:
  - - name: x-dataset-config
      template: x-dataset-config
      arguments: {}
  - - name: y-dataset-config
      template: y-dataset-config
      arguments: {}
  - - name: escape-x
      template: escape-quotes
      arguments:
        parameters:
          - name: data
            value: '{{steps.x-dataset-config.outputs.result}}'
  - - name: escape-y
      template: escape-quotes
      arguments:
        parameters:
          - name: data
            value: '{{steps.y-dataset-config.outputs.result}}'
  - - name: train-model-works
      template: train-model-works
      arguments:
        parameters:
          - name: dataset_configs
            value: >-
              ["{{steps.escape-x.outputs.result}}",
              "{{steps.escape-y.outputs.result}}"]
    - name: train-model-fails-1
      template: train-model-fails
      arguments:
        parameters:
          - name: dataset_configs
            value: >-
              ["{{steps.x-dataset-config.outputs.result}}",
              "{{steps.y-dataset-config.outputs.result}}"]
    - name: train-model-fails-2
      template: train-model-fails
      arguments:
        parameters:
          - name: dataset_configs
            value: >-
              ["{{steps.escape-x.outputs.result}}",
              "{{steps.escape-y.outputs.result}}"]
```

This is how the failed step looks on Argo UI 
![image](https://github.com/argoproj-labs/hera/assets/4072778/5f9e5400-bd94-46df-8a21-8d3adb59f601)
