### ISSUE TITLE
If Container(volume_mounts) exists Container(volumes) doesnt get write out in yaml

### ISSUE THREAD

**Issue by mozarik** [argoproj-labs/hera#835]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [ ] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_
If i define `volume_mounts[]` and `volumes[]` in `Container()` the only thing that got write out to yaml is the `volume_mounts`. 

_Error log if applicable_:
```
No Error Log
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
with Workflow(
    generate_name="test-",
    volumes=[
        SecretVolume(name="service-account-credential",secret_name="service-account-credential")
    ],
    entrypoint="test"
) as w2:
    v_tmp_pod = Volume(
        name="tmp-pod",
        size="100Mi",
        mount_path="/tmp/pod",
    )
    init_container_example = Container(
        name="git-sync",
        volume_mounts=[
            VolumeMount(name="service-account-credential", mount_path="/secrets")
        ],
        volumes=[v_tmp_pod]
    )
    with Steps(name="test") as s:
        init_container_example()

print(w2.to_yaml())
```
output:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: argo-staging
spec:
  entrypoint: test
  templates:
  - container:
      image: python:3.8
      volumeMounts:
      - mountPath: /secret
        name: service-account-credential
    name: git-sync
  - name: test
    steps:
    - - name: git-sync
        template: git-sync
  volumeClaimTemplates:
  - metadata:
      name: tmp-pod
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
  volumes:
  - name: service-account-credential
    secret:
      secretName: service-account-credential
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

It should be volume_mounts + volumes in the `volume_mounts`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: argo-staging
spec:
  entrypoint: test
  templates:
  - container:
      image: python:3.8
      volumeMounts:
      - mountPath: /secrets
        name: service-account-credential
      - mountPath: /tmp/pod
        name: tmp-pod
    name: git-sync
  - name: test
    steps:
    - - name: git-sync
        template: git-sync
  volumeClaimTemplates:
  - metadata:
      name: tmp-pod
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
  volumes:
  - name: service-account-credential
    secret:
      secretName: service-account-credential
```

**Environment**
 - Version of Hera: 5.9.0
 - Version of Argo: [e.g. 3.5.0]
