### ISSUE TITLE
Using an input artifact locks the /tmp/hera folder for outputs

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#841]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [x] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [ ] No
(Open to discussion whether to file an issue upstream)

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When using an input artifact, at the default location of `/tmp/hera/inputs/artifacts/...`, the folders are created with root permissions. This blocks hera outputs within the same script, with an error that looks like

```
Traceback (most recent call last):
  File "/opt/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hera/outputs/parameters'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/.../hera/workflows/runner.py", line 313, in <module>
    _run()
  File "/.../hera/workflows/runner.py", line 306, in _run
    result = _runner(args.entrypoint, kwargs_list)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../hera/workflows/runner.py", line 277, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
  File "/.../hera/workflows/runner.py", line 211, in _save_annotated_return_outputs
    _write_to_path(path, output_value)
  File "/.../hera/workflows/runner.py", line 231, in _write_to_path
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.11/pathlib.py", line 1120, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/hera/outputs'
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from typing import Annotated

from hera.workflows import (
    Artifact,
    Parameter,
    Step,
    Steps,
    Script,
    WorkflowTemplate,
    global_config,
    script,
)

global_config.set_class_defaults(Script, constructor="runner")
global_config.experimental_features["script_runner"] = True
global_config.experimental_features["script_annotations"] = True

@script()
def create_artifact(
    message_param_input: Annotated[str, Parameter(name="message-param-input")]
) -> Annotated[str, Artifact(name="message-artifact")]:
    """Prints out a message."""
    return message_param_input

@script()
def convert_artifact(
    message_art_input: Annotated[str, Artifact(name="message-art-input")]
) -> Annotated[str, Parameter(name="message-param-output")]:
    """Prints out a message."""
    return message_art_input

with WorkflowTemplate(
    name="test-input-outputs",
    entrypoint="steps",
) as wt:
    with Steps(name="steps"):
        create = create_artifact(arguments={"message-param-input": "Hello world"})
        convert_artifact(
            arguments=[
                create.get_artifact("message-artifact").with_name(
                    "message-art-input"
                )
            ]
        )
```

We can workaround this by setting the default inputs/outputs directories to be distinct from the first folder under `/tmp`, i.e. `/tmp/hera-inputs` and `/tmp/hera-outputs`.

We can also recreate the problem in yaml, and confirm the file permissions:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-input-outputs-
spec:
  entrypoint: containers
  templates:
  - container:
      args:
      - echo '{{inputs.parameters.message}}' | tee /tmp/output_artifact.txt
      command:
      - sh
      - -c
      image: docker/whalesay:latest
    inputs:
      parameters:
      - name: message
    name: create-artifact-container
    outputs:
      artifacts:
      - name: message-artifact
        path: /tmp/output_artifact.txt
  - container:
      args:
      - ls -al /tmp; cat /tmp/some-folder/input_artifact.txt; mkdir /tmp/another-folder;
        mkdir /tmp/some-folder/sub-folder
      command:
      - sh
      - -c
      image: docker/whalesay:latest
    inputs:
      artifacts:
      - name: message-artifact
        path: /tmp/some-folder/input_artifact.txt
    name: use-artifact-container
  - name: containers
    steps:
    - - arguments:
          parameters:
          - name: message
            value: Hello world
        name: create-artifact
        template: create-artifact-container
    - - arguments:
          artifacts:
          - from: '{{steps.create-artifact.outputs.artifacts.message-artifact}}'
            name: message-artifact
        name: use-artifact
        template: use-artifact-container
```

Which basically runs the following commands:
```console
ls -al /tmp
cat /tmp/some-folder/input_artifact.txt
mkdir /tmp/another-folder
mkdir /tmp/some-folder/sub-folder
```

and gets the following logs in the `use-artifact-container`:

```
total 0
drwxrwxrwt 1 root root 25 Nov  6 12:03 .
drwxr-xr-x 1 root root 28 Nov  6 12:03 ..
drwxr-xr-x 2 root root 32 Nov  6 12:03 some-folder
Hello world
mkdir: cannot create directory '/tmp/some-folder/sub-folder': Permission denied
time="2023-11-06T12:03:53 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

Notice how `some-folder` is root ownership, so the `sub-folder` has permission denied, which is what our Hera runner is doing. 

**Question - should this be reported upstream?** It's probably "WAD" that the folder is created with root perms, and we should split out the folders.

**Expected behavior**
Hera outputs to work even in the presence of input artifacts.

**Environment**
 - Version of Hera: 5.9.0
 - Version of Argo: 3.4.8

**Additional context**
