### ISSUE TITLE
HTTPGetAction "port: int" will output as string in yaml 

### ISSUE THREAD

**Issue by mozarik** [argoproj-labs/hera#869]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When defining Probe inside of `UserContainer`

```
startup_probe=Probe(
    http_get=HTTPGetAction(path="/startup", port=9801, scheme="HTTP"),
    timeoutSeconds=10,
    periodSeconds=1,
    successThreshold=1,
    failureThreshold=60
)
```

The output of startupProbe will look like this

```
  startupProbe:
    httpGet:
      path: /startup
      port: '9801'
      scheme: HTTP
    timeoutSeconds: 10
    periodSeconds: 1
    successThreshold: 1
    failureThreshold: 60
 ```  
 
 Error message when running the workflow
 
 ```
 Pod "rg-custom-drill-daily-s4gj9-pod-179047205" is invalid: [spec.containers[2].lifecycle.preStop.httpGet.port: Invalid value: "9091": must contain at least one letter (a-z), spec.containers[2].livenessProbe.httpGet.port: Invalid value: "9801": must contain at least one letter (a-z), spec.containers[2].startupProbe.httpGet.port: Invalid value: "9801": must contain at least one letter (a-z)]
 ```

**Expected behavior**
Expected the port is not string

```
  startupProbe:
    httpGet:
      path: /startup
      port: 9801
      scheme: HTTP
    timeoutSeconds: 10
    periodSeconds: 1
    successThreshold: 1
    failureThreshold: 60
 ```  

**Environment**
- Hera Version: 5.9.0
- Python: 3.9
- Argo Workflow: 3.5.0-rc1
